version: '3.4'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__CERTIFICATES__DEFAULT__PATH=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__CERTIFICATES__DEFAULT__PASSWORD=youtube
    volumes:
      - ~/.aspnet/https:/https
    depends_on:
      - db
    ports:
      - 8080:8080
      - 8081:8081
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tikTakToeDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d tikTakToeDb'" ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
    driver: local